---
 - name: configure libvirtd
   template:
     src: libvirtd.conf.j2
     dest: "{{ ansible_role_vmlab_conf_path }}"
     owner: root
     group: root
     mode: 0644
   notify: restart_libvirtd

 - name: ensure libvirtd is running
   service:
     name: "{{ ansible_role_vmlab_service_name }}"
     state: started
     enabled: true

 - name: add users to libvirtd group
   user:
     name: "{{ item }}"
     groups: "{{ ansible_role_vmlab_user_group }}"
     append: yes
   with_items: "{{ ansible_role_vmlab_users }}"

 - name: ensure vmlandscape mountpoint
   file:
     path: "{{ item.value.mountpoint }}"
     owner: "{{ ansible_role_vmlab_user_group }}"
     group: "{{ ansible_role_vmlab_user_group }}"
     state: directory
   with_dict: '{{ ansible_role_vmlab_pools }}'

 - name: define vmlandscape pools
   virt_pool:
     uri: '{{ ansible_role_vmlab.qstring }}'
     name: '{{ item.key }}'
     xml: '{{ lookup("template", "dir.xml.jp2") }}'
     mode: overwrite
     state: present
     autostart: yes
   with_dict: '{{ ansible_role_vmlab_pools }}'
   notify: autostart_landscape_pools

 - name: activate vmlandscape pools
   virt_pool:
     uri: '{{ ansible_role_vmlab.qstring }}'
     name: '{{ item.key }}'
     state: active
     autostart: yes
   with_dict: '{{ ansible_role_vmlab_pools }}'
   notify: autostart_landscape_pools

 - name: define vmlandscape nets
   virt_net:
     uri: '{{ ansible_role_vmlab.qstring }}'
     name: '{{ item.key }}'
     xml: '{{ lookup("template", "net.xml.jp2") }}'
     command: define
   with_dict: '{{ ansible_role_vmlab_nets }}'
   notify: autostart_landscape_nets

 - name: start vmlandscape nets
   virt_net:
     uri: '{{ ansible_role_vmlab.qstring }}'
     name: '{{ item.key }}'
     autostart: yes
     state: active
   with_dict: '{{ ansible_role_vmlab_nets }}'
   notify: autostart_landscape_nets

 - name: create dirs in vmlandscape control dir
   file:
     path: "{{ ansible_role_vmlab.mntpointcontrol }}/{{ item }}"
     state: directory
     owner: root
     mode: g+rws
     group: '{{ ansible_role_vmlab_user_group }}'
   with_items:
   - sbin
   - bin
   - isos
   - public_html

 - name: create shell
   template:
     src: "create-vm.sh.j2"
     dest: "{{ ansible_role_vmlab.mntpointcontrol }}/bin/create-vm-{{ item.key }}.sh"
     mode: 0755
     owner: root
     group: root
   tags:
   - shell
   with_dict: "{{ ansible_role_vmlab_virtoses }}"

 - name: install apache
   package:
     name: apache2

 - name: enable service
   service:
     name: apache2
     state: started
     enabled: true

 - name: install vmlandscape preseed host configuration
   template:
     src: vmlandscape.conf.j2
     dest: /etc/apache2/sites-available/vmlandscape.conf
   notify: apache_reload

 - name: symlink vmlandscape to sites-enabled
   file:
     src: ../sites-available/vmlandscape.conf
     dest: /etc/apache2/sites-enabled/vmlandscape.conf
     state: link
   notify: apache_reload

 - name: create deployment dirs
   file:
     dest: "{{ ansible_role_vmlab.mntpointcontrol }}/public_html/{{ item }}"
     state: directory
   with_items:
   - opensuse
   - debian
   tags:
   - shell

 - name: deploy preseed
   template:
     src: "{{ item }}.preseed.j2"
     dest: "{{ ansible_role_vmlab.mntpointcontrol }}/public_html/{{ item }}/{{ item }}.preseed"
   with_items:
   - opensuse
   - debian
   tags:
   - shell

 - name: deploy superuser scripts
   copy:
     src: "sbin/{{ item }}"
     dest: "{{ ansible_role_vmlab.mntpointcontrol }}/sbin/{{ item }}"
     mode: 0755
   with_items:
   - vm-destroy.sh

 - name: deploy clone script with user context
   template:
     src: debian-base-9-clone.sh.j2
     dest: "{{ ansible_role_vmlab.mntpointcontrol }}/sbin/debian-base-9-clone.sh"
     mode: 0755
