---
 - name: ensure installed libvirt
   package:
     name: libvirt-daemon-system
     default-release: "{{ ansible_distribution_release }}-backports"

 - name: debug
   debug:
     var: ansible_role_vmlab_python_packages

 - name: ensure python support for libvirt
   package:
     name: "{{ item }}"
   with_items: "{{ ansible_role_vmlab_python_packages }}"
